[package]
name = "wsbroad"
version = "0.1.0"
authors = ["Vitaly _Vi Shukela <vi0oss@gmail.com>"]

[dependencies]
futures-await = { version = "0.1" }
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
websocket = { version = "0.20", default-features = false, features = ["async"]}
#take_mut = "0.2"
compactmap = "^0.2.1"
